# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20170929_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='capacity',
            field=models.IntegerField(max_length=32, verbose_name='磁盘容量GB'),
        ),
    ]
